# Generated by Django 3.2 on 2021-06-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(default='text', max_length=10),
        ),
    ]
