# Generated by Django 3.2 on 2021-06-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='aud_img',
            field=models.FileField(blank=True, null=True, upload_to='aud_img/'),
        ),
        migrations.AddField(
            model_name='message',
            name='msg_img',
            field=models.ImageField(blank=True, null=True, upload_to='msg_img/'),
        ),
        migrations.AddField(
            model_name='message',
            name='pdf_img',
            field=models.FileField(blank=True, null=True, upload_to='pdf_img/'),
        ),
        migrations.AddField(
            model_name='message',
            name='vid_img',
            field=models.FileField(blank=True, null=True, upload_to='vid_img/'),
        ),
    ]
